# Generated by Django 5.0.6 on 2024-06-24 01:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Guild',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id_user_creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guildas_criadas', to=settings.AUTH_USER_MODEL)),
                ('id_user_members', models.ManyToManyField(related_name='guild_members', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
