# Generated by Django 5.0.6 on 2024-06-23 22:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guild', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guild',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 6, 23, 22, 41, 6, 50269, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
